In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 100)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import os

data_path = "/content/drive/MyDrive/dsce/online_learning/OnlineLearningCourses.csv"

# File size in MB
size_mb = os.path.getsize(data_path) / (1024**2)

# Load CSV
df = pd.read_csv(data_path)

rows, cols = df.shape
size_mb, rows, cols

(0.031213760375976562, 500, 10)

In [5]:
df.head()

,User_ID,Experience_Level,Course_Type,Platform,Hours_Spent_Per_Week,Course_Duration_Weeks,Completion_Status,Completion_Percentage,Dropout_Reason,Satisfaction_Score
0,U0001,Fresher,Tech,Skillshare,16,8,Completed,67,No Dropout,2
1,U0002,Fresher,Non-Tech,edX,17,22,Dropped,38,Time Constraint,3
2,U0003,Fresher,Non-Tech,Coursera,19,21,In Progress,43,No Dropout,1
3,U0004,Student,Non-Tech,Udemy,14,2,Dropped,14,Time Constraint,1
4,U0005,Student,Non-Tech,Skillshare,8,10,Dropped,8,Too Difficult,4

In [6]:
df.dtypes

User_ID                  object
Experience_Level         object
Course_Type              object
Platform                 object
Hours_Spent_Per_Week      int64
Course_Duration_Weeks     int64
Completion_Status        object
Completion_Percentage     int64
Dropout_Reason           object
Satisfaction_Score        int64
dtype: object

In [7]:
df.isna().mean().sort_values(ascending=False).head(15)

User_ID                  0.0
Experience_Level         0.0
Course_Type              0.0
Platform                 0.0
Hours_Spent_Per_Week     0.0
Course_Duration_Weeks    0.0
Completion_Status        0.0
Completion_Percentage    0.0
Dropout_Reason           0.0
Satisfaction_Score       0.0
dtype: float64

In [8]:
df.columns.tolist()

['User_ID',
 'Experience_Level',
 'Course_Type',
 'Platform',
 'Hours_Spent_Per_Week',
 'Course_Duration_Weeks',
 'Completion_Status',
 'Completion_Percentage',
 'Dropout_Reason',
 'Satisfaction_Score']